### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by xxl-game** [akof1314/Unity-EditorInternalsVisibleDemo#1]
请问声明友元程序集这一步是怎么做的？需要用工具修改 UnityEditor.dll 吗？ 

我把项目直接拉下来就能用，但 UnityEditor.dll 这个文件不是应该在我本地的Unity安装目录里吗，我还没有修改 dll 怎么就已经生效了。

如果把包从package文件夹挪到Asset文件夹，就无效了，这个必须放在包里吗。

**Comment by xxl-game** [comment]
啊，我误解了，本来以为Facebook是后加进去的，原来是Unity自带的，只是占用了这个名字。

**Comment by akof1314** [comment]
是的，欺骗了Unity编辑器，然后就可以友元了
